import { Routes } from '@angular/router';

import {DashboardComponent} from './view/dashboard.component';
import {DashboardAnalyticsComponent} from './view/dashboardanalytics.component';
import {FormLayoutDemoComponent} from './view/formlayoutdemo.component';
import {InvalidStateDemoComponent} from './view/invalidstatedemo.component';
import {PanelsDemoComponent} from './view/panelsdemo.component';
import {OverlaysDemoComponent} from './view/overlaysdemo.component';
import {MediaDemoComponent} from './view/mediademo.component';
import {MenusDemoComponent} from './view/menusdemo.component';
import {MessagesDemoComponent} from './view/messagesdemo.component';
import {MiscDemoComponent} from './view/miscdemo.component';
import {EmptyDemoComponent} from './view/emptydemo.component';
import {ChartsDemoComponent} from './view/chartsdemo.component';
import {FileDemoComponent} from './view/filedemo.component';
import {DocumentationComponent} from './view/documentation.component';

import {AppNotfoundComponent} from '../pages/theme/app.notfound.component';
import {AppContactusComponent} from '../pages/theme/app.contactus.component';
import {AppErrorComponent} from '../pages/theme/app.error.component';
import {AppAccessdeniedComponent} from '../pages/theme/app.accessdenied.component';
import {AppLoginComponent} from '../pages/theme/app.login.component';
import {AppLandingComponent} from '../pages/theme/app.landing.component';
import {InputDemoComponent} from './view/inputdemo.component';
import {FloatLabelDemoComponent} from './view/floatlabeldemo.component';
import {ButtonDemoComponent} from './view/buttondemo.component';
import {TableDemoComponent} from './view/tabledemo.component';
import {ListDemoComponent} from './view/listdemo.component';
import {AppTimelineDemoComponent} from '../pages/theme/app.timelinedemo.component';
import {TreeDemoComponent} from './view/treedemo.component';
import {DisplayComponent} from '../utilities/display.component';
import {ElevationComponent} from '../utilities/elevation.component';
import {FlexboxComponent} from '../utilities/flexbox.component';
import {GridComponent} from '../utilities/grid.component';
import {IconsComponent} from '../utilities/icons.component';
import {WidgetsComponent} from '../utilities/widgets.component';
import {SpacingComponent} from '../utilities/spacing.component';
import {TypographyComponent} from '../utilities/typography.component';
import {TextComponent} from '../utilities/text.component';
import {AppCrudComponent} from '../pages/theme/app.crud.component';
import {AppCalendarComponent} from '../pages/theme/app.calendar.component';
import {AppInvoiceComponent} from '../pages/theme/app.invoice.component';
import {AppHelpComponent} from '../pages/theme/app.help.component';
import {AppWizardComponent} from '../pages/theme/app.wizard.component';

export const DemoRoutingModule: Routes = [

          {path: 'dashboard', component: DashboardComponent},
          {path: 'dashboardanalytics', component: DashboardAnalyticsComponent},
          {path: 'uikit/formlayout', component: FormLayoutDemoComponent},
          {path: 'uikit/floatlabel', component: FloatLabelDemoComponent},
          {path: 'uikit/invalidstate', component: InvalidStateDemoComponent},
          {path: 'uikit/input', component: InputDemoComponent},
          {path: 'uikit/button', component: ButtonDemoComponent},
          {path: 'uikit/table', component: TableDemoComponent},
          {path: 'uikit/list', component: ListDemoComponent},
          {path: 'uikit/tree', component: TreeDemoComponent},
          {path: 'uikit/panel', component: PanelsDemoComponent},
          {path: 'uikit/overlay', component: OverlaysDemoComponent},
          {path: 'uikit/menu', component: MenusDemoComponent},
          {path: 'uikit/media', component: MediaDemoComponent},
          {path: 'uikit/message', component: MessagesDemoComponent},
          {path: 'uikit/misc', component: MiscDemoComponent},
          {path: 'uikit/charts', component: ChartsDemoComponent},
          {path: 'uikit/file', component: FileDemoComponent},
          {path: 'utilities/display', component: DisplayComponent},
          {path: 'utilities/elevation', component: ElevationComponent},
          {path: 'utilities/flexbox', component: FlexboxComponent},
          {path: 'utilities/grid', component: GridComponent},
          {path: 'utilities/icons', component: IconsComponent},
          {path: 'utilities/widgets', component: WidgetsComponent},
          {path: 'utilities/spacing', component: SpacingComponent},
          {path: 'utilities/typography', component: TypographyComponent},
          {path: 'utilities/text', component: TextComponent},
          {path: 'pages/crud', component: AppCrudComponent},
          {path: 'pages/calendar', component: AppCalendarComponent},
          {path: 'pages/timeline', component: AppTimelineDemoComponent},
          {path: 'pages/invoice', component: AppInvoiceComponent},
          {path: 'pages/help', component: AppHelpComponent},
          {path: 'pages/empty', component: EmptyDemoComponent},
          {path: 'documentation', component: DocumentationComponent},
  
  {path: 'error', component: AppErrorComponent},
  {path: 'access', component: AppAccessdeniedComponent},
  {path: 'notfound', component: AppNotfoundComponent},
  {path: 'contactus', component: AppContactusComponent},
  {path: 'login', component: AppLoginComponent},
  {path: 'landing', component: AppLandingComponent},
  {path: 'pages/wizard', component: AppWizardComponent},
  {path: '**', redirectTo: '/notfound'},
]